name: Salt Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install salt-lint
        run: |
          pip install salt-lint

      - name: Run salt-lint
        run: |
          salt-lint salt/ pillar/
